### ISSUE TITLE
Is indy-docker maintained?

### ISSUE THREAD

**Issue by tadayosi** [Commonjava/indy-docker#29]
Is this project maintained?  Or is it abandoned?  If so, what's the best way to run indy as a container?  Thanks.

**Comment by ligangty** [comment]
Hi @tadayosi We are still maintain the indy image here: https://github.com/Commonjava/commonjava-images/tree/master/indy
And the image is hosted here: https://quay.io/repository/factory2/indy The newest tag is 2.7.2.

**Comment by tadayosi** [comment]
Super! That's what I'm looking for. Thank you!
